version: "3.9"
services:
  food-truck-backend:
    build: .
    environment:
      - ENV=production
      - DEBUG=0
      - LOG_LEVEL=INFO
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5002
      - CONCURRENCY=2
      - JWT_SECRET=whatever
    ports:
      - 5002:5002
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  postgres:
    image: postgis/postgis:14-3.3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d postgres -U root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
